sudo: false

language: go
go:
  - 1.7
  - tip

install:
  - go get -v github.com/Masterminds/glide
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install

script:
  - ./.travis/test.sh
  - gometalinter.v1 --deadline=5m --vendor --disable=gotype --disable=errcheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
