language: go

go:
  - 1.5
  - tip

install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/require
  - go get github.com/gorilla/mux
  - go get github.com/sirupsen/logrus
  - go get github.com/tehnerd/gnl2go
  - go get github.com/fsouza/go-dockerclient

script:
  - ./.travis/script.sh . core disco pulse util gorb-docker-link

after_success:
  - bash <(curl -s https://codecov.io/bash)
